### ISSUE TITLE
Blackwell GPU support (Compute Capability 12.0)

### ISSUE THREAD

**Issue by ShayekhBinIslam** [QwenLM/Qwen3-Omni#83]
### Description

Cannot run the model in Blackwell GPU with CC 12.0

### Reproduction

`docker run --gpus all --name qwen3-omni \
		-v /var/run/docker.sock:/var/run/docker.sock -p $$HOST_PORT:$$CONTAINER_PORT \
		--mount type=bind,source=$$LOCAL_WORKDIR,target=/data/shared/Qwen3-Omni \
		--shm-size=4gb \
		-it qwenllm/qwen3-omni:3-cu124`

`python web_demo.py`

### Logs

```shell
(VllmWorkerProcess pid=300) INFO 10-14 11:09:20 [multiproc_worker_utils.py:226] Worker ready; awaiting tasks
(VllmWorkerProcess pid=300) INFO 10-14 11:09:21 [cuda.py:363] Using Flash Attention backend.
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:287: UserWarning:
NVIDIA RTX PRO 6000 Blackwell Server Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA RTX PRO 6000 Blackwell Server Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
(VllmWorkerProcess pid=300) /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:287: UserWarning:
(VllmWorkerProcess pid=300) NVIDIA RTX PRO 6000 Blackwell Server Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
(VllmWorkerProcess pid=300) The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
(VllmWorkerProcess pid=300) If you want to use the NVIDIA RTX PRO 6000 Blackwell Server Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
(VllmWorkerProcess pid=300)
(VllmWorkerProcess pid=300)   warnings.warn(
(VllmWorkerProcess pid=300) INFO 10-14 11:09:22 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=300) INFO 10-14 11:09:22 [pynccl.py:70] vLLM is using nccl==2.26.2
INFO 10-14 11:09:22 [__init__.py:1152] Found nccl from library libnccl.so.2
INFO 10-14 11:09:22 [pynccl.py:70] vLLM is using nccl==2.26.2
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/shared/Qwen3-Omni/web_demo.py", line 377, in <module>
[rank0]:     model, processor = _load_model_processor(args)
[rank0]:   File "/data/shared/Qwen3-Omni/web_demo.py", line 33, in _load_model_processor
[rank0]:     model = LLM(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 271, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 501, in from_engine_args
[rank0]:     return engine_cls.from_vllm_config(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 477, in from_vllm_config
[rank0]:     return cls(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 265, in __init__
[rank0]:     self.model_executor = executor_class(vllm_config=vllm_config)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 287, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 53, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/mp_distributed_executor.py", line 125, in _init_executor
[rank0]:     self._run_workers("init_device")
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/mp_distributed_executor.py", line 186, in _run_workers
[rank0]:     driver_worker_output = run_method(self.driver_worker, sent_method,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/utils/__init__.py", line 2736, in run_method
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 606, in init_device
[rank0]:     self.worker.init_device()  # type: ignore
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 193, in init_device
[rank0]:     init_worker_distributed_environment(self.vllm_config, self.rank,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 534, in init_worker_distributed_environment
[rank0]:     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1095, in ensure_model_parallel_initialized
[rank0]:     initialize_model_parallel(tensor_model_parallel_size,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1037, in initialize_model_parallel
[rank0]:     _TP = init_model_parallel_group(group_ranks,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 832, in init_model_parallel_group
[rank0]:     return GroupCoordinator(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 255, in __init__
[rank0]:     self.device_communicator = device_comm_cls(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/cuda_communicator.py", line 50, in __init__
[rank0]:     self.pynccl_comm = PyNcclCommunicator(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 105, in __init__
[rank0]:     data = torch.zeros(1, device=device)
[rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239] Exception in worker VllmWorkerProcess while processing method init_device.
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239] Traceback (most recent call last):
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 233, in _run_worker_process
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils/__init__.py", line 2736, in run_method
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     return func(*args, **kwargs)
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 606, in init_device
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     self.worker.init_device()  # type: ignore
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 193, in init_device
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     init_worker_distributed_environment(self.vllm_config, self.rank,
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 534, in init_worker_distributed_environment
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1095, in ensure_model_parallel_initialized
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     initialize_model_parallel(tensor_model_parallel_size,
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 1037, in initialize_model_parallel
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     _TP = init_model_parallel_group(group_ranks,
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 832, in init_model_parallel_group
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     return GroupCoordinator(
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 255, in __init__
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     self.device_communicator = device_comm_cls(
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/cuda_communicator.py", line 50, in __init__
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     self.pynccl_comm = PyNcclCommunicator(
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 105, in __init__
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]     data = torch.zeros(1, device=device)
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239] RuntimeError: CUDA error: no kernel image is available for execution on the device
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(VllmWorkerProcess pid=300) ERROR 10-14 11:09:23 [multiproc_worker_utils.py:239]
INFO 10-14 11:09:23 [multiproc_worker_utils.py:125] Killing local vLLM worker processes
[rank0]:[W1014 11:09:24.336273206 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

### Environment Information

CUDA: 13.0 Blackwell GPU

### Known Issue

- [x] The issue hasn't been already addressed in Documentation, Issues, and Discussions.

**Comment by sarmiena** [comment]
@ShayekhBinIslam You can try to build from source instead of using the container, or build your own container. Here's what worked for me using SM120 (Blackwell)

```
git clone https://github.com/vllm-project/vllm.git
cd vllm
uv venv
source .venv/bin/activate
VLLM_USE_PRECOMPILED=1 uv pip install -e .
uv pip install qwen-omni-utils -U
uv pip install vllm[audio]
vllm serve Qwen/Qwen3-Omni-30B-A3B-Instruct
```

OR

```
uv venv
source .venv/bin/activate
uv pip install -U vllm --pre --extra-index-url https://wheels.vllm.ai/nightly
uv pip install vllm[audio]
vllm serve Qwen/Qwen3-Omni-30B-A3B-Instruct 
```

**Comment by ShayekhBinIslam** [comment]
Thank you, solved~!
